### ISSUE TITLE
你这个插件功能和select2有点类似，再说，jq插件现在基本全了，不全的自己写了，现在发布出来的没有以前多了

### ISSUE THREAD

**Issue by LeachZhou** [qxchen6/jq-selector#1]

**Comment by qxchen6** [comment]
你好，我就是用了select2所以才自己造的轮子。有两个原因，第一个是因为我需要的功能很少，只要可以多选，可以远程搜索就可以。select2明显太大了。不过这不是主要问题，主要问题是：select2有一个我们产品经理受不了的地方，就是select2在使用多选的时候，每选一项，就会收起下拉框。需要再次展开来选下一项。并且我没有找到“多选时不收起”的配置项，产品经理又要求，于是就自己写了个简单的。
